services:
  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      APP_NAME: "ProjectManagerApp"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/task_manager"
      SPRING_DATASOURCE_USERNAME: "myuser"
      SPRING_DATASOURCE_PASSWORD: "mypassword"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "mypassword"
      POSTGRES_DB: "task_manager"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data: