### Get all tasks
GET http://localhost:8080/tasks

### Create new task
POST http://localhost:8080/tasks
Content-Type: application/json

{
  "title": "Wyslac sprawko",
  "description": "Wyslac sprawko do niedzieli i otworzyc PR",
  "taskType": "HIGH_PRIORITY",
  "project": {
    "id": 1,
    "name": "lab2"
  }
}

### Get all projects
GET http://localhost:8080/projects

### Create new project
POST http://localhost:8080/projects
Content-Type: application/json

{
  "name": "lab2"
}

### Get all users
GET http://localhost:8080/users

### Create new user
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "olek"
}