services:
  app:
    build: .
    container_name: project-manager-app
    ports:
      - "3000:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/project_manager
      - SPRING_DATASOURCE_USERNAME=project_user
      - SPRING_DATASOURCE_PASSWORD=project_pass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    
  db:
    image: postgres:15-alpine
    container_name: project-manager-db
    environment:
      - POSTGRES_DB=project_manager
      - POSTGRES_USER=project_user
      - POSTGRES_PASSWORD=project_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U project_user -d project_manager"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: