version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: jira_db
      POSTGRES_USER: jira_user
      POSTGRES_PASSWORD: jira_pass
    ports:
      - "15432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jira_db
      SPRING_DATASOURCE_USERNAME: jira_user
      SPRING_DATASOURCE_PASSWORD: jira_pass
    depends_on:
      - db