version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: projectmanager
      POSTGRES_USER: pmuser
      POSTGRES_PASSWORD: pmsecret
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/projectmanager
      SPRING_DATASOURCE_USERNAME: pmuser
      SPRING_DATASOURCE_PASSWORD: pmsecret

volumes:
  db-data:
