version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: projectmanager-postgres
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: projectuser
      POSTGRES_PASSWORD: projectpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - projectmanager-network

  app:
    build: .
    container_name: projectmanager-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/task_manager
      SPRING_DATASOURCE_USERNAME: projectuser
      SPRING_DATASOURCE_PASSWORD: projectpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
    ports:
      - "8080:8080"
    networks:
      - projectmanager-network

volumes:
  postgres_data:

networks:
  projectmanager-network:
    driver: bridge