services:
  db:
    image: postgres:15
    container_name: project_manager_db
    environment:
      POSTGRES_DB: project_manager
      POSTGRES_USER: project_manager
      POSTGRES_PASSWORD: project_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U project_manager -d project_manager"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    container_name: project_manager_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/project_manager
      SPRING_DATASOURCE_USERNAME: project_manager
      SPRING_DATASOURCE_PASSWORD: project_manager
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge