version: '3.8'

services:
  app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/task_manager
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=kapi2000
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  db:
    image: postgres
    container_name: task_manager
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kapi2000
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"