version: '2.1'
services:
  server:
    container_name: server
    build:
      context: .
    ports:
      - 8083:8080
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
  postgres:
    image: 'postgres:latest'
    ports:
      - 25432:5432
    volumes:
      - ./var/db-data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root" ]
      interval: 5s
      timeout: 5s
      retries: 5
